### ISSUE TITLE
Segmentation fault on Crunchbang linux. 

### ISSUE THREAD

**Issue by ajpen** [GhostSquad57/Steam-Installer-for-Wheezy#47]
I have no idea what causes it. 
![screenshot - 08012015 - 05 54 21 pm](https://cloud.githubusercontent.com/assets/4834786/9023732/67d84814-3876-11e5-9883-3607922f8ab9.png)

**Comment by GhostSquad57** [comment]
Isn't Crunchbang no longer being developed; if I not mistaken the last update was like 2 years ago. 

I would recommend installing a newer distro  release (e.g., Debian, Fedora, Ubuntu etc.) and installing Steam from the official repositories of the distro you pick.

**Comment by ajpen** [comment]
https://crunchbangplusplus.org/

Its dead but its not dead, dead.

**Comment by GhostSquad57** [comment]
Does Crunchbang++ use the same repos as Debian Jessie? If so, `apt-get install steam` should work fine and my package shouldn't be necessary.

**Comment by ajpen** [comment]
I believe so. Ill try it, thanks

**Comment by GhostSquad57** [comment]
@ajpen Have you had any luck?

**Comment by ajpen** [comment]
Haven't tried as yet. Will try this evening and let you know.
